server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # React Router를 위한 fallback 라우팅 설정 (SPA)
        try_files $uri $uri/ /index.html;
    }

    # 불필요한 에러 로그 방지
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
}
